// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1-cq5LiStsx1ldxjX44qa5RUWhr36FI',
    appId: '1:316850270153:web:c6afd695164ed8c47c4218',
    messagingSenderId: '316850270153',
    projectId: 'menu-random-bf9ef',
    authDomain: 'menu-random-bf9ef.firebaseapp.com',
    storageBucket: 'menu-random-bf9ef.firebasestorage.app',
    measurementId: 'G-DEKE9JVJ29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWlM1DONCgAs-EKcpPInWlgJUoxgomt8',
    appId: '1:316850270153:android:8f17de56227c41657c4218',
    messagingSenderId: '316850270153',
    projectId: 'menu-random-bf9ef',
    storageBucket: 'menu-random-bf9ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3xye5ldF6ca-9gqBzbK48Y7UVEbxRLX4',
    appId: '1:316850270153:ios:2042d2d3f23d3f7c7c4218',
    messagingSenderId: '316850270153',
    projectId: 'menu-random-bf9ef',
    storageBucket: 'menu-random-bf9ef.firebasestorage.app',
    iosClientId: '316850270153-brjdu7ih3s3t0ldnib7heqir8bs89jfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3xye5ldF6ca-9gqBzbK48Y7UVEbxRLX4',
    appId: '1:316850270153:ios:2042d2d3f23d3f7c7c4218',
    messagingSenderId: '316850270153',
    projectId: 'menu-random-bf9ef',
    storageBucket: 'menu-random-bf9ef.firebasestorage.app',
    iosClientId: '316850270153-brjdu7ih3s3t0ldnib7heqir8bs89jfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV1-cq5LiStsx1ldxjX44qa5RUWhr36FI',
    appId: '1:316850270153:web:066c2bb13faf1f687c4218',
    messagingSenderId: '316850270153',
    projectId: 'menu-random-bf9ef',
    authDomain: 'menu-random-bf9ef.firebaseapp.com',
    storageBucket: 'menu-random-bf9ef.firebasestorage.app',
    measurementId: 'G-HEWZXFM5LH',
  );
}
