// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BCW3FEwKmOt6C0IWOAHIg0vf6Ph5Tvo',
    appId: '1:842950010320:web:0be8ec72c86567b82cc5d5',
    messagingSenderId: '842950010320',
    projectId: 'cheapshaker',
    authDomain: 'cheapshaker.firebaseapp.com',
    storageBucket: 'cheapshaker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBO5enSwBR6CgAN4Hd__3I5ripo1PptU',
    appId: '1:842950010320:android:059c7d2308929e982cc5d5',
    messagingSenderId: '842950010320',
    projectId: 'cheapshaker',
    storageBucket: 'cheapshaker.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQEDbeEeSaggKorlhq8qfbHyWlOk-PblI',
    appId: '1:842950010320:ios:34958b1abd91a0ae2cc5d5',
    messagingSenderId: '842950010320',
    projectId: 'cheapshaker',
    storageBucket: 'cheapshaker.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQEDbeEeSaggKorlhq8qfbHyWlOk-PblI',
    appId: '1:842950010320:ios:34958b1abd91a0ae2cc5d5',
    messagingSenderId: '842950010320',
    projectId: 'cheapshaker',
    storageBucket: 'cheapshaker.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0BCW3FEwKmOt6C0IWOAHIg0vf6Ph5Tvo',
    appId: '1:842950010320:web:f01a3381ba84e6792cc5d5',
    messagingSenderId: '842950010320',
    projectId: 'cheapshaker',
    authDomain: 'cheapshaker.firebaseapp.com',
    storageBucket: 'cheapshaker.firebasestorage.app',
  );
}
